language: python
services:
  - docker
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - pytest
  - docker build -t cadueceus:latest .
  - docker images
deploy:
  provider: script
  script: bash dockerhub
  on:
    branch: main